wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: huggingface
    huggingface_version: 4.5.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1630055929
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      3:
      - 2
      4: 3.7.0
      5: 0.12.0
      6: 4.5.0
      8:
      - 5
architecture:
  desc: null
  value: Bert+CRF
bert_learning_rate:
  desc: null
  value: 2.0e-05
dataset:
  desc: null
  value: 3195-train,791-dev
other_learning_rate:
  desc: null
  value: 0.002
train_batch_size:
  desc: null
  value: 48
